new_start_api:
    resource: "@newStartAPIBundle/Controller/"
    type:     annotation
    prefix:   /

new_start_common:
    resource: "@newStartCommonBundle/Controller/"
    type:     annotation
    prefix:   /

_security_check:
    pattern:  /login_fb_check

_security_logout:
    pattern:  /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_security_check:
  pattern:  /login_fb_check
_security_logout:
  pattern:  /logout
#_facebook_secured:
#  pattern: /secured/
