new_start_api:
    resource: "@newStartAPIBundle/Controller/"
    type:     annotation
    prefix:   /

new_start_common:
    resource: "@newStartCommonBundle/Controller/"
    type:     annotation
    prefix:   /

new_start_user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

_security_check:
  pattern:  /login_fb_check
_security_logout:
  pattern:  /logout

