new_start_api:
    resource: "@newStartAPIBundle/Controller/"
    type:     annotation
    prefix:   /

new_start_common:
    resource: "@newStartCommonBundle/Controller/"
    type:     annotation
    prefix:   /

_security_check:
    pattern:  /fb_login_check

_security_logout:
    pattern:  /fb_logout

_facebook_secured:
    pattern: /secured/
    defaults: { _controller: CommonBundle:Default:index }
