new_start_api:
    resource: "@newStartAPIBundle/Controller/"
    type:     annotation
    prefix:   /

new_start_common:
    resource: "@newStartCommonBundle/Controller/"
    type:     annotation
    prefix:   /

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"

_facebook_secured:
    pattern: /secured/
    defaults: { _controller: CommonBundle:Default:index }
