imports:
    - { resource: facebookParameters.ini }
    
jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
         chain:
             providers: [fos_userbundle, my_fos_facebook_provider]
        my_fos_facebook_provider:
            id: my.facebook.user
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:        
        main:
            pattern: ^/
            fos_facebook:
                app_url: %facebookAppUrl%
                server_url: %facebookServerUrl%
                #login_path: /login
                check_path: /login_fb_check
                #default_target_path: /
                provider: my_fos_facebook_provider
                success_handler: my_fos_facebook_auth_success_handler
            anonymous: true
            logout:
                path: /logout
                target: public_home

    access_control:
        # FOS facebook
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
